# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - sui move build
      - echo "build done"
    sources:
      - sources/**/*.move
      - Move.toml
  test:
    cmds:
      - sui move test
    sources:
      - sources/**/*.move
      - Move.toml
  demo:
    deps:
      - build
    cmds:
      - pnpm ts-node examples/demo.ts
    sources:
      - src/**/*.ts
      - examples/**/*.ts
      - .env
